### ISSUE TITLE
How to disable cache for authorized users?

### ISSUE THREAD

**Issue by nullproduction** [barryvdh/laravel-httpcache#10]
Hello. Thank you for the lib.
I'd like show cached pages only for not authorized users.
How to make it?

**Comment by barryvdh** [comment]
I think you could best add the middleware conditionally in your Kernel.

```php
protected function handle($request)
	{
		if (\Auth::guest())
		{
			$this->prependMiddleware('Barryvdh\HttpCache\Middleware\CacheRequests');
		}
 
		return parent::handle($request);
	}
```

**Comment by nullproduction** [comment]
@barryvdh Thank you for help. I think it good solution.
