### ISSUE TITLE
Laravel 5.1 comaptibility

### ISSUE THREAD

**Issue by UnrulyNatives** [barryvdh/laravel-httpcache#11]
Hi, I was trying to upgrade to L5.1 by using composer. I got this problem: `requires Illuminate/support 5.0.x`.

Any chances you could upgrade your composer.json list?

**Comment by barryvdh** [comment]
Updated composer.json

**Comment by pchrysa** [comment]
even though I updated I had to rollback to 5.0 because it still says that laravel-httpcache is not compatible with 5.1

**Comment by barryvdh** [comment]
It wasn't tagged yet. Should be now (`v0.2.2`)

**Comment by pchrysa** [comment]
Problem 1
    - Installation request for barryvdh/laravel-httpcache 0.2.2 -> satisfiable by barryvdh/laravel-httpcache[v0.2.2].
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - barryvdh/laravel-httpcache v0.2.2 requires barryvdh/laravel-stack-middleware 0.2.* -> satisfiable by barryvdh/laravel-stack-middleware[v0.2.0].
    - barryvdh/laravel-stack-middleware v0.2.0 requires illuminate/support 5.0.x -> satisfiable by laravel/framework[v5.0.33], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - barryvdh/laravel-stack-middleware v0.2.0 requires illuminate/support 5.0.x -> satisfiable by laravel/framework[v5.0.33], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - Can only install one of: laravel/framework[v5.1.0, v5.0.33].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.2].

**Comment by barryvdh** [comment]
Ah, I've also tagged `barryvdh/laravel-stack-middleware` `v0.2.1`, try that in a few minutes?

**Comment by pchrysa** [comment]
Perfect! thanks
