### ISSUE TITLE
ESI: Illuminate request expected

### ISSUE THREAD

**Issue by jeroenvandergeer** [barryvdh/laravel-httpcache#13]
I've been trying to get the ESI rendering to work in a regular Laravel 5/5.1 install. 
There seem to be a few issues that I'm running into that you may have resolved already.

The (sub)request generated by the ESI service is a Symfony request instead of a Illuminate request. Several Laravel services expect the Illuminate request and, without setting the factory callable on the Symfony request class to return a Illumate request, the application will crash straight away.

Replacing the request will allow the request to go through, but it will never be handled by the Illuminate kernel (it's handled by your ClosureHttpKernel instead). All default middleware will therefore never run, and again crash the application.

Did you manage to get this to work?

Edit: I didn't add the middlewares at the top in my kernel, doing so will make the other middlewares run on the subrequest.

**Comment by Shawnley** [comment]
Temporary fix: 
in _Barryvdh\HttpCache\Middleware\ParseEsi.php_ change
`$response = $next($request);`
to
`$response = $next(Request::createFromBase($request));`

**Comment by jeroenvandergeer** [comment]
That might be better than what I did. I set the factory on the Symfony Request class: 

        Symfony\Component\HttpFoundation\Request::setFactory(function (array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null) {
            return new \Illuminate\Http\Request($query, $request, $attributes, $cookies, $files, $server, $content);
        });

This will then return a Illuminate request:

    Symfony\Component\HttpFoundation\Request::create() 

Chances are that you don't always want this, and it's better to replace it in the context of the HttpCache.

**Comment by tomvo** [comment]
I've done some tests as well and it seems the fix from @Shawnley holds up. Any chance this change can get applied in the library?

**Comment by barryvdh** [comment]
Soo, the above commit fixes it?

If not, please re-open.

**Comment by tomvo** [comment]
It seems to work for normal requests but there seems to be a problem with injecting stuff. I'm also using your debugbar package and when I combine the debugbar with ESI includes in my page something weird happens. I can't put my finger on it since I don't know much about how the content injection from the debugbar package works.
When I enable the debugbar on a page with ESI the document content stops with this as the last line at the bottom of the HTML: `<link rel="styl`

**Comment by barryvdh** [comment]
It just appends some string in the responce content. Not sure why it would be stripped half way.

**Comment by tomvo** [comment]
Yeah but removing the ESI include or the Surrogate-Controler solves this. Must have to do something with the ESI parsing by Symfony then i guess?
