### ISSUE TITLE
a simple question.

### ISSUE THREAD

**Issue by ctf0** [barryvdh/laravel-httpcache#22]
hi there, many thanx for this package, i was going through learning more about `varnish` and this seems to be to do all i want without getting into to much server jargon,
however there is something i cant quite understand and i googled for quite sometime but without any actual result, so my question is

> as stated on blade docs that views gets cached and then changed when the included partials inside it is updated which is good,
but now i read about ESI and i cant see what exactly is the benefit of it if blade + some ajax does exactly the same.

**Comment by barryvdh** [comment]
The benefit is that you don't use ajax.

**Comment by ctf0** [comment]
perfect but let me extend the question a bit further, lets say that we have a partial with some data that will be included into the main page when the user login, doesn't blade handle that natively  ?

if there any chance u can point me to an example to make things more clearer i would deeply appreciate it.
