### ISSUE TITLE
Session not store on request

### ISSUE THREAD

**Issue by ebisbe** [barryvdh/laravel-httpcache#31]
Hello @barryvdh ,

I implemented the httpcache with your settings and testing it on my local environment with docker worked fine. When uploading the change ( with the docker also ) it broke and got 'Session not store on request' for some calls that where private. 

Your middleware was added:
```
    protected $middleware = [
        \Barryvdh\HttpCache\Middleware\CacheRequests::class,
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];
```
So all request where checked if they had a httpcache page. In the documentation doesn't says anything about where to put that. And I'm wondering if this middleware disables somehow the session.

Can you guide me a little on that issue?

thanks

**Comment by ebisbe** [comment]
Hello, 

I've found that happens when the app is set to production.

**Comment by bjora857** [comment]
Not sure its the exact same thing.
But I also had problems with the session after have added `\Barryvdh\HttpCache\Middleware\CacheRequests::class` to the $middleware array.

I was using code like this. To display flash messages.
`return back()->with('flash_message', 'Requested invalidation of images.');`
And the flash messages never went away.

So what I ended up doing was removing 

` \Barryvdh\HttpCache\Middleware\CacheRequests::class` from the $middleware array

 And then added the middleware only for the routes that I wanted to cache (they never interact with the session)
 
` Route::get('/', ['as' => 'start', 'uses' => 'StartController@index'])->middleware(\Barryvdh\HttpCache\Middleware\CacheRequests::class);
`

 It seemed to solved my issues.

**Comment by ebisbe** [comment]
Yes @bjora857 It's the same issue but mine only happened on production environment.

**Comment by timhaak** [comment]
Just adding had the same problem.

Following https://github.com/barryvdh/laravel-httpcache/issues/38#issuecomment-323555840

I moved the middleware to the protected $middlewareGroups under web and it fixed the problem. 

If anyone else is having the same problem.
