### ISSUE TITLE
Barryvdh\HttpCache\Middleware\SetTtl does not exist

### ISSUE THREAD

**Issue by patrikden** [barryvdh/laravel-httpcache#36]
Version 0.2.7 installed on laravel 5.4.
When try:
```
Route::get('/', ['as' => 'index', 'uses' => 'IndexController@index'])->middleware('ttl:60');
```

Got this error:
```
 ReflectionException
Class Barryvdh\HttpCache\Middleware\SetTtl does not exist
```

In laravel-httpcache/src/Middleware folder only this files:
```
CacheRequests.php
ParseEsi.php
```

**Comment by barryvdh** [comment]
Try the 1.x dev version

**Comment by patrikden** [comment]
When try get 1.x dev this warning message:
```
Problem 1
    - The requested package barryvdh/laravel-httpcache 1.x exists as barryvdh/laravel-httpcache[dev-master, 0.3.x-dev, v0.1, v0.1.1, v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.3.0] but these are rejected by your constraint.
```

I try install 0.3.0 have the same files in folder :(
```
CacheRequests.php
ParseEsi.php
```

If you could add SetTtl to package it will be awesome! Thank you!

**Comment by patrikden** [comment]
Sorry, after update to 0.3.0 SetTtl.php in folder too, thats ok :)

Now I try add middleware to route
```
Route::get('/', ['as' => 'index', 'uses' => 'IndexController@index'])->middleware('ttl:62');
```

And there are no new files in httpcache folder, but in Cache-Control header i can see:
```
Cache-Control:public, s-maxage=62
```

**Comment by patrikden** [comment]
fixed problem, thanks :)
