### ISSUE TITLE
Laravel 5.5 - ClearCommand::handle() does not exist

### ISSUE THREAD

**Issue by luukverhoeven** [barryvdh/laravel-httpcache#45]
After upgrading to laravel 5.5 Artisan::call('httpcache:clear'); causes the follow  error.

  [ReflectionException]
  Method Barryvdh\HttpCache\Console\ClearCommand::handle() does not exist

**Comment by luukverhoeven** [comment]
Adding the function below to ClearCommand will solve this issue.

 public function handle()
    {
        $this->fire();
    }

**Comment by barryvdh** [comment]
Can you submit a PR?

**Comment by GrahamCampbell** [comment]
This is already fixed, just not tatgged: https://github.com/barryvdh/laravel-httpcache/compare/v0.3.0...master.

**Comment by taufek** [comment]
Requesting to have this fix released

**Comment by barryvdh** [comment]
Tagged
