### ISSUE TITLE
Error HttpFoundation\Request::isMethodSafe() is deprecated

### ISSUE THREAD

**Issue by boonstoppel** [barryvdh/laravel-httpcache#48]
Symfony\Component\HttpFoundation\Request::isMethodSafe() is deprecated since version 3.2 and will throw an exception in 4.0. 

Disable checking only for cacheable methods by calling the method with false as first argument or use the Request::isMethodCacheable() instead.

**Comment by boonstoppel** [comment]
any updates on this? I submitted a pull request to fix this issue.

**Comment by boonstoppel** [comment]
Created a new pull request that is backward compatible:
https://github.com/barryvdh/laravel-httpcache/pull/51

**Comment by barryvdh** [comment]
Fixed with https://github.com/barryvdh/laravel-httpcache/commit/ff09bf7405371941acec2ffaab852353b7fb315b

**Comment by barryvdh** [comment]
Can you try with `0.3@dev`?

**Comment by boonstoppel** [comment]
works like a charm
