### ISSUE TITLE
Unresolvable dependency issue

### ISSUE THREAD

**Issue by grimmdude** [barryvdh/laravel-httpcache#5]
Very interested in trying out this service provider but I'm getting this error when all loaded up:

```
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider
```

Any ideas?  Thanks,

-Garrett

**Comment by barryvdh** [comment]
You are using a fresh L5 install?

**Comment by grimmdude** [comment]
Thanks for the reply.  Using L5 but not fresh; it's been in development for about a month.  I'm trying to trace it back but not having much luck, do you have any ideas why that would be happening?

Also, to confirm `'Barryvdh\HttpCache\ServiceProvider',` needs to be added to app/Http/Kernel.php correct?

**Comment by grimmdude** [comment]
Nope, I see the issue.  I didn't use the right namspace in the `$middleware` array.  :\  Thanks for getting back to me so quickly in any case.
