### ISSUE TITLE
Disabling the cache does not work

### ISSUE THREAD

**Issue by andrey-helldar** [barryvdh/laravel-httpcache#53]
In file `config/httpcache.php` there is an option `enabled`, the value of which is set from the `env` file:
```php
'enabled'   => env('HTTPCACHE_ENABLE', true),
```

I tried setting the value of this variable to different values:
```env
HTTPCACHE_ENABLE=
HTTPCACHE_ENABLE=0
HTTPCACHE_ENABLE=false
HTTPCACHE_ENABLE=null
```

But none of the options work. The application still caches pages.

Also, in the package code I did not find where the caching disable key is used.

The impossibility of disabling the package is hampered by the fact that during the project layout, each time it is necessary to run the console command to clear the cache and only then refresh the page in the browser.
Therefore, the use of "live reload" becomes meaningless.

**Comment by andrey-helldar** [comment]
On the production server, the package works perfectly. But when developing, the inability to turn off causes many problems.

**Comment by andrey-helldar** [comment]
Does this problem worry only me?

**Comment by andrey-helldar** [comment]
@barryvdh, hello!
Perhaps you just have no time to deal with this project, but I want to remind you of your problem.
The package has a key to disable caching, but it does not work and is not used anywhere. I added this feature in my #54 PR.
Thanks!

**Comment by mmodler** [comment]
@barryvdh 
Can you please tag a release? The bug is annoying because it caches my form security tokens in an admin area...

**Comment by mmodler** [comment]
Thanks!

Seems like PyroCMS uses the "Direct approach, without ServiceProvider" so the issue persists :(
