### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by andrey-helldar** [barryvdh/laravel-httpcache#55]
Tell me how soon to wait for support Laravel 6.0?
A new version of the framework has been officially released.

**Comment by barryvdh** [comment]
I tagged one, can you test?

**Comment by andrey-helldar** [comment]
Yes. I'll be at work in two hours and I can check. Thank!

**Comment by andrey-helldar** [comment]
@barryvdh, yep, it's works!
Thank you!
