### ISSUE TITLE
[question] Purging with wildcards?

### ISSUE THREAD

**Issue by tomvo** [barryvdh/laravel-httpcache#8]
So i've implement the httpcache middleware and all is fine. However I'm trying to figure out what the best way is to purge the cache. Url as key works but my url's can differ and I'm not sure how HttpCache is storing them.For example one URL that will be cached might be: `/photos?user=1&taken=01-01-2015`

Will HttpCache use a hash of this url as key for the cache record? So will `/photos?user=2&taken=01-02-2015` have a different cache entry?
Then: A photo can be in both results, how do I invalidate them both when the photo changes? Will `->purge('/photos*');` invalidate both those cache entries?

Thanks

**Comment by barryvdh** [comment]
I think both urls are seen as different resources and will get different cache objects. I'm not sure if it's possible to wildcard purge.
Here is the section on the docs: http://symfony.com/doc/current/book/http_cache.html#cache-invalidation

It is possible within this library, so I might need to take a look there: http://foshttpcache.readthedocs.org/en/latest/cache-invalidator.html

**Comment by tomvo** [comment]
Ah right, yeah I checked the source and they are different hashes indeed, so different cache entries.
The FOSHttpCache lib does allow to do invalidates but not purges yet: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/183

Any hints on how I might be able - currently - to know which /photos/* cache entries exist and just delete them all. Maybe by fetching them first?

**Comment by barryvdh** [comment]
Not sure, sorry.
Can't you just clear the entire cache or is that too radical?

**Comment by tomvo** [comment]
It's radical but possible, I'm caching a lot of stuff though, lot of heavy stuff which would be affected then. One kind of dirty trick is tracking the cached url on forehand in the laravel cache as a collection or simple array. Put the TTL on the same value as the cache TTL and then fetch the url's and purge them.

**Comment by tomvo** [comment]
I've indeed managed to do this using a collection of URL's stored in memcache and then purging them on specific events in my application. I guess that was the easiest way of doing this for now.
