### ISSUE TITLE
View responses break HttpCache in Symfony

### ISSUE THREAD

**Issue by RyanThompson** [barryvdh/laravel-httpcache#9]
When returning a view from a controller, everything breaks cause it's not an instance of Response..

I tried simply overriding the HttpCache but it's entirely private (annoying) so had to copy the file. 

Any thoughts on how to remedy this in a more elegant manner?

I also tried checking the response type prior and converting to response object but it's no use if you have to evaluate the response to test it - cache is missed at that point.

Here is all I did to catch it: https://github.com/anomalylabs/streams-platform/commit/4550c2035930f835984f61a5dc336c4584f3363f#diff-8811282b9f527c7bce6daf4944b4ebe5R489

**Comment by barryvdh** [comment]
Is this also the case when you add it as a global middleware? (In the app kernel?)

**Comment by RyanThompson** [comment]
Interesting, it is NOT. How can I mimic that behavior? I would like to keep the streams-platform package using your package decoupled from it's laravel base as much as I can.

**Comment by barryvdh** [comment]
Hmm not really sure, probably the rendering of the view happens after the middleware runs. Which does seem odd..
This kinda looks like the same issue you have, but is assumed to be fixed..
https://github.com/laravel/framework/pull/7454

**Comment by RyanThompson** [comment]
Looks like middle ware from the app is passed through before any of the controller stuff is. Shoot.. Not the end of the world though, thanks for the heads up!
